// Mobile app — bilingual UI strings. All user data (balance, quests, tasks,
// wins) comes from the backend; this file only holds static copy + the coach's
// offline fallback replies.
export type Lang = 'es' | 'en';

/** Tier-1 coach fallback lines, used when the on-device LLM is off/unavailable. */
export const REPLIES: Record<Lang, string[]> = {
  es: [
    'Pregúntate: ¿lo necesito o solo lo deseo? El deseo pasa; la meta queda.',
    'Empieza pequeño: aparta el 10% apenas te paguen, antes de gastar nada.',
    'Un fondo de emergencia son 3 a 6 meses de gastos. Es tu armadura contra el caos.',
    'Si esperas 24 horas y aún lo quieres, quizá valga. Casi nunca lo querrás igual.',
  ],
  en: [
    'Ask yourself: do I need it, or do I just want it? The want fades; the goal stays.',
    'Start small: set aside 10% the moment you get paid, before you spend anything.',
    'An emergency fund is 3 to 6 months of expenses. It is your armor against chaos.',
    'If you wait 24 hours and still want it, maybe it is worth it. You rarely will.',
  ],
};

const es = {
  nav: { home: 'Inicio', tasks: 'Tareas', coach: 'Mentor', learn: 'Misiones', goals: 'Metas' },
  conn: {
    waking: 'Despertando a tu cochinita…',
    errTitle: 'No pudimos conectar',
    errBody: 'Revisa tu internet e inténtalo de nuevo.',
    retry: 'Reintentar',
  },
  ob: {
    eyebrow: 'TU MENTOR FINANCIERO ZEN',
    title1: 'Ahorra con calma.',
    title2: 'Gasta con propósito.',
    sub: 'Aprende finanzas con una cochinita estoica que te enseña a no comprar por impulso.',
    f1: 'Domina tus impulsos',
    f1d: 'Reta tus antojos antes de pagar',
    f2: 'Misiones de dinero',
    f2d: 'Aprende un concepto a la vez',
    f3: 'Mentor con IA',
    f3d: 'La cochinita responde tus dudas',
    cta: 'Empezar',
    login: 'Ya tengo cuenta',
  },
  home: {
    hi: 'Hola de nuevo',
    level: 'NIVEL',
    balLabel: 'AHORRADO ESTE MES',
    xp: 'EXPERIENCIA',
    chEyebrow: 'RETO DEL DÍA',
    chTitle: 'Resiste la tentación',
    chBody: 'Apareció un antojo. Respira y decide con la cabeza fría.',
    chCta: 'Aceptar reto',
    questEyebrow: 'MISIÓN ACTUAL',
    questCta: 'Continuar misión',
    askEyebrow: 'PREGÚNTALE A LA COCHINITA',
    askBody: '¿Gastar o ahorrar? Tu mentor estoico te ayuda a decidir.',
    tip: '"La riqueza consiste no en tener grandes posesiones, sino en tener pocas necesidades."',
    tipAuthor: '— EPICTETO',
  },
  coach: {
    name: 'Cochinita Zen',
    status: 'EN LÍNEA',
    placeholder: 'Escribe tu duda...',
    intro:
      'Respira. Antes de gastar, preguntémonos: ¿esto te acerca a tu meta o solo calma un impulso?',
    s1: '¿Cómo empiezo a ahorrar?',
    s2: '¿Vale la pena este antojo?',
    s3: '¿Qué es un fondo de emergencia?',
    aiTitle: 'Coach IA en el teléfono',
    aiHint: 'Gratis y privado. Descarga única (~300 MB).',
    aiLoading: 'Descargando coach…',
    disclaimer: 'IA en tu teléfono · puede equivocarse',
    report: 'Reportar',
  },
  settings: {
    title: 'Ajustes',
    legalSection: 'LEGAL',
    privacy: 'Política de privacidad',
    terms: 'Términos y condiciones',
    helpSection: 'AYUDA',
    contact: 'Contactar soporte',
    report: 'Reportar un problema',
    accountSection: 'CUENTA',
    logout: 'Cerrar sesión',
    deleteAccount: 'Eliminar cuenta',
    deleteTitle: '¿Eliminar la cuenta?',
    deleteBody:
      'Solo tu mamá o papá puede borrar la cuenta. Le enviaremos un correo para confirmarlo. ¿Enviar la solicitud?',
    deleteSend: 'Enviar solicitud',
    deleteCancel: 'Cancelar',
    deleteDoneTitle: 'Solicitud enviada',
    deleteDoneBody: 'Le avisamos a tu mamá o papá para que elimine la cuenta desde su panel.',
    deleteFooter:
      'Tu cuenta la creó y la administra tu mamá o papá. También pueden eliminarla desde el panel de padres.',
    aiNote:
      'La Cochinita Zen es una IA en tu teléfono. Puede equivocarse — habla con un adulto sobre decisiones de dinero.',
    version: 'Versión',
  },
  templ: {
    eyebrow: 'RETO · RESISTE EL IMPULSO',
    wantLabel: 'APARECIÓ UN ANTOJO',
    wantBody: 'Los viste en oferta. Tu mente dice "ahora o nunca". Tu cochinita dice: respira.',
    breatheCta: 'Respira antes de decidir',
    breathing: 'Inhala… exhala…',
    breathingSub: 'Deja que el impulso pase',
    decideQ: 'El impulso bajó. ¿Qué decides?',
    resist: 'Resistir',
    buyAnyway: 'Comprar de todos modos',
    wonTitle: 'Mente fría.',
    wonBody: 'Resististe. Ese dinero ahora trabaja para tu meta, no para un capricho.',
    wonQuote: '"No es pobre el que tiene poco, sino el que desea más."',
    wonAuthor: '— SÉNECA',
    wonCta: 'Volver al inicio',
    again: 'Otro reto',
    boughtTitle: 'Sin culpa.',
    boughtBody:
      'A veces compramos. Lo estoico es notarlo y elegir mejor la próxima vez. Aprendiste algo de ti.',
    boughtCta: 'Entendido',
    resistedLabel: 'RESISTIDOS',
  },
  tasks: {
    title: 'Mis tareas',
    sub: 'Asignadas por mamá. Complétalas y gana.',
    earnLabel: 'PUEDES GANAR ESTA SEMANA',
    todo: 'POR HACER',
    pending: 'ESPERANDO A MAMÁ',
    approved: 'APROBADA ✓',
    recur: { once: 'Una vez', daily: 'Diaria', weekly: 'Semanal', monthly: 'Mensual' },
    dueToday: 'Vence hoy',
    dueTomorrow: 'Vence mañana',
    dueIn: 'Vence en {n} días',
    overdue: 'Vencida',
  },
  lessons: {
    title: 'Misiones',
    sub: 'Aprende finanzas, una quest a la vez',
    done: 'COMPLETADA',
    prog: 'EN CURSO',
    locked: 'BLOQUEADA',
    toDo: 'POR HACER',
    start: 'Empezar lección',
    review: 'Repasar',
    cont: 'Continuar',
    check: 'Comprobar',
    question: 'Pregunta',
    of: 'de',
    correct: '¡Correcto!',
    almost: 'Casi…',
    passTitle: '¡Lección completada!',
    passSub: 'Aprendiste algo nuevo. Sigue así.',
    failTitle: 'Repasemos un poco',
    failSub: 'Revisa las tarjetas e inténtalo otra vez.',
    xpEarned: 'XP ganada',
    levelUp: '¡Subiste de nivel!',
    moneyEarned: 'Ganaste',
    claim: 'Reclamar recompensa',
    retry: 'Intentar de nuevo',
    reviewNote: 'Repaso — ya reclamaste esta lección.',
    close: 'Cerrar',
    historyTitle: 'Completadas',
  },
  wins: {
    title: 'Logros',
    sub: 'Tu camino estoico con el dinero',
    earned: 'OBTENIDO',
    locked: 'BLOQUEADO',
    stat1: 'NIVEL',
    stat2: 'RACHA',
    stat3: 'RESISTIDOS',
  },
  goals: {
    title: 'Metas',
    sub: 'Sueña, planea y alcánzalo',
    mySection: 'MIS METAS',
    logrosSection: 'LOGROS',
    empty: 'Aún no tienes metas. ¡Crea tu primera!',
    add: 'Nueva meta',
    max: 'Puedes tener hasta 3 metas.',
    saved: 'Ahorrado',
    of: 'de',
    achieved: '¡LOGRADA!',
    delete: 'Eliminar',
    deleteConfirm: '¿Eliminar esta meta?',
    cancel: 'Cancelar',
    monthOne: '~1 mes',
    monthsN: '~{n} meses',
    term: { short: 'Corto plazo', medium: 'Mediano plazo', long: 'Largo plazo' },
    cat: { thing: 'Algo que quiero', invest: 'Invertir y crecer', learn: 'Aprender' },
    sheetTitle: 'Elige una meta',
    tabSuggested: 'Sugeridas',
    tabCustom: 'Personalizada',
    customSub: 'Elige tu propio nombre y monto',
    nameLabel: 'Nombre de la meta',
    namePh: 'Ej. Bicicleta nueva',
    targetLabel: 'Meta en $',
    targetPh: '60',
    termLabel: '¿En cuánto tiempo?',
    catLabel: 'Tipo de meta',
    create: 'Crear meta',
  },
  // 7 tiers, beginner → expert (index = level - 1).
  levels: [
    'Principiante',
    'Ahorrador',
    'Planificador',
    'Inversionista',
    'Estratega',
    'Maestro',
    'Experto',
  ],
};

const en: typeof es = {
  nav: { home: 'Home', tasks: 'Tasks', coach: 'Coach', learn: 'Quests', goals: 'Goals' },
  conn: {
    waking: 'Waking up your piggy…',
    errTitle: "Couldn't connect",
    errBody: 'Check your internet and try again.',
    retry: 'Retry',
  },
  ob: {
    eyebrow: 'YOUR ZEN MONEY MENTOR',
    title1: 'Save with calm.',
    title2: 'Spend with purpose.',
    sub: 'Learn money skills with a stoic little pig who teaches you to resist impulse buys.',
    f1: 'Master your impulses',
    f1d: 'Challenge your urges before you pay',
    f2: 'Money quests',
    f2d: 'Learn one concept at a time',
    f3: 'AI mentor',
    f3d: 'The piggy answers your questions',
    cta: 'Get started',
    login: 'I already have an account',
  },
  home: {
    hi: 'Welcome back',
    level: 'LEVEL',
    balLabel: 'SAVED THIS MONTH',
    xp: 'EXPERIENCE',
    chEyebrow: 'DAILY CHALLENGE',
    chTitle: 'Resist the temptation',
    chBody: 'An urge appeared. Breathe and decide with a cool head.',
    chCta: 'Take the challenge',
    questEyebrow: 'CURRENT QUEST',
    questCta: 'Continue quest',
    askEyebrow: 'ASK THE PIGGY',
    askBody: 'Spend or save? Your stoic mentor helps you decide.',
    tip: '"Wealth consists not in having great possessions, but in having few wants."',
    tipAuthor: '— EPICTETUS',
  },
  coach: {
    name: 'Zen Piggy',
    status: 'ONLINE',
    placeholder: 'Type your question...',
    intro:
      'Breathe. Before you spend, let us ask: does this move you toward your goal, or just calm an urge?',
    s1: 'How do I start saving?',
    s2: 'Is this urge worth it?',
    s3: 'What is an emergency fund?',
    aiTitle: 'On-device AI coach',
    aiHint: 'Free and private. One-time download (~300 MB).',
    aiLoading: 'Downloading coach…',
    disclaimer: 'On-device AI · may be wrong',
    report: 'Report',
  },
  settings: {
    title: 'Settings',
    legalSection: 'LEGAL',
    privacy: 'Privacy Policy',
    terms: 'Terms & Conditions',
    helpSection: 'HELP',
    contact: 'Contact support',
    report: 'Report a problem',
    accountSection: 'ACCOUNT',
    logout: 'Sign out',
    deleteAccount: 'Delete account',
    deleteTitle: 'Delete the account?',
    deleteBody:
      'Only your mom or dad can delete the account. We will email them to confirm. Send the request?',
    deleteSend: 'Send request',
    deleteCancel: 'Cancel',
    deleteDoneTitle: 'Request sent',
    deleteDoneBody: 'We let your parent know so they can delete the account from their dashboard.',
    deleteFooter:
      'Your account was created and is managed by your parent. They can also delete it from the parent dashboard.',
    aiNote:
      'Zen Piggy is an AI on your phone. It can be wrong — talk to a grown-up about money decisions.',
    version: 'Version',
  },
  templ: {
    eyebrow: 'CHALLENGE · RESIST THE URGE',
    wantLabel: 'AN URGE APPEARED',
    wantBody: 'You saw them on sale. Your mind says "now or never". Your piggy says: breathe.',
    breatheCta: 'Breathe before deciding',
    breathing: 'Inhale… exhale…',
    breathingSub: 'Let the urge pass',
    decideQ: 'The urge faded. What do you choose?',
    resist: 'Resist',
    buyAnyway: 'Buy it anyway',
    wonTitle: 'Cool mind.',
    wonBody: 'You resisted. That money now works for your goal, not for a whim.',
    wonQuote: '"It is not the man who has too little, but the man who craves more, that is poor."',
    wonAuthor: '— SENECA',
    wonCta: 'Back to home',
    again: 'Another challenge',
    boughtTitle: 'No guilt.',
    boughtBody:
      'Sometimes we buy. The stoic move is to notice it and choose better next time. You learned something.',
    boughtCta: 'Got it',
    resistedLabel: 'RESISTED',
  },
  tasks: {
    title: 'My tasks',
    sub: 'Assigned by mom. Finish them and earn.',
    earnLabel: 'YOU CAN EARN THIS WEEK',
    todo: 'TO DO',
    pending: 'WAITING FOR MOM',
    approved: 'APPROVED ✓',
    recur: { once: 'One-time', daily: 'Daily', weekly: 'Weekly', monthly: 'Monthly' },
    dueToday: 'Due today',
    dueTomorrow: 'Due tomorrow',
    dueIn: 'Due in {n} days',
    overdue: 'Overdue',
  },
  lessons: {
    title: 'Quests',
    sub: 'Learn money skills, one quest at a time',
    done: 'COMPLETED',
    prog: 'IN PROGRESS',
    locked: 'LOCKED',
    toDo: 'TO DO',
    start: 'Start lesson',
    review: 'Review',
    cont: 'Continue',
    check: 'Check',
    question: 'Question',
    of: 'of',
    correct: 'Correct!',
    almost: 'Almost…',
    passTitle: 'Lesson complete!',
    passSub: 'You learned something new. Keep it up.',
    failTitle: "Let's review a bit",
    failSub: 'Look over the cards and try again.',
    xpEarned: 'XP earned',
    levelUp: 'You leveled up!',
    moneyEarned: 'You earned',
    claim: 'Claim reward',
    retry: 'Try again',
    reviewNote: 'Review — you already claimed this lesson.',
    close: 'Close',
    historyTitle: 'Completed',
  },
  wins: {
    title: 'Wins',
    sub: 'Your stoic journey with money',
    earned: 'EARNED',
    locked: 'LOCKED',
    stat1: 'LEVEL',
    stat2: 'STREAK',
    stat3: 'RESISTED',
  },
  goals: {
    title: 'Goals',
    sub: 'Dream it, plan it, reach it',
    mySection: 'MY GOALS',
    logrosSection: 'ACHIEVEMENTS',
    empty: 'No goals yet. Create your first one!',
    add: 'New goal',
    max: 'You can have up to 3 goals.',
    saved: 'Saved',
    of: 'of',
    achieved: 'ACHIEVED!',
    delete: 'Delete',
    deleteConfirm: 'Delete this goal?',
    cancel: 'Cancel',
    monthOne: '~1 month',
    monthsN: '~{n} months',
    term: { short: 'Short term', medium: 'Medium term', long: 'Long term' },
    cat: { thing: 'Something I want', invest: 'Invest & grow', learn: 'Learn & grow' },
    sheetTitle: 'Choose a goal',
    tabSuggested: 'Suggested',
    tabCustom: 'Custom',
    customSub: 'Pick your own name and amount',
    nameLabel: 'Goal name',
    namePh: 'e.g. New bicycle',
    targetLabel: 'Target in $',
    targetPh: '60',
    termLabel: 'How soon?',
    catLabel: 'Goal type',
    create: 'Create goal',
  },
  levels: ['Beginner', 'Saver', 'Planner', 'Investor', 'Strategist', 'Master', 'Expert'],
};

export type AppStrings = typeof es;
export const STR: Record<Lang, AppStrings> = { es, en };
