import type { TaskCategory, TaskPayType } from '@stoicpiggy/shared';

export type SuggestionGroup = 'home' | 'study' | 'homework' | 'financial';

export interface TaskSuggestion {
  es: string;
  en: string;
  group: SuggestionGroup;
  category: TaskCategory;
  payType: TaskPayType;
  /** Whole dollars; 0 when payType is 'xp'. */
  amount: number;
  xp: number;
  /** Inclusive age range this task fits (4–18). */
  minAge: number;
  maxAge: number;
}

/**
 * 50 curated, age-appropriate task ideas for kids 4–18, across four groups
 * (home / study / homework / financial). Picking one fills the create-task
 * form; age filtering uses [minAge, maxAge]. Money amounts scale with age.
 */
export const TASK_SUGGESTIONS: readonly TaskSuggestion[] = [
  // ── Home (chores) ─────────────────────────────────────────────
  {
    es: 'Guardar los juguetes',
    en: 'Put away the toys',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 1,
    xp: 20,
    minAge: 4,
    maxAge: 7,
  },
  {
    es: 'Poner la ropa sucia en el cesto',
    en: 'Put dirty clothes in the hamper',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 1,
    xp: 20,
    minAge: 4,
    maxAge: 8,
  },
  {
    es: 'Hacer la cama',
    en: 'Make the bed',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 1,
    xp: 25,
    minAge: 5,
    maxAge: 12,
  },
  {
    es: 'Dar de comer a la mascota',
    en: 'Feed the pet',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 2,
    xp: 30,
    minAge: 5,
    maxAge: 14,
  },
  {
    es: 'Poner la mesa',
    en: 'Set the table',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 1,
    xp: 25,
    minAge: 5,
    maxAge: 12,
  },
  {
    es: 'Regar las plantas',
    en: 'Water the plants',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 1,
    xp: 20,
    minAge: 6,
    maxAge: 14,
  },
  {
    es: 'Recoger los platos de la mesa',
    en: 'Clear the dishes',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 2,
    xp: 30,
    minAge: 6,
    maxAge: 14,
  },
  {
    es: 'Limpiar tu cuarto',
    en: 'Clean your room',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 2,
    xp: 30,
    minAge: 7,
    maxAge: 16,
  },
  {
    es: 'Sacar la basura',
    en: 'Take out the trash',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 2,
    xp: 30,
    minAge: 8,
    maxAge: 18,
  },
  {
    es: 'Barrer el piso',
    en: 'Sweep the floor',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 2,
    xp: 30,
    minAge: 8,
    maxAge: 16,
  },
  {
    es: 'Doblar la ropa',
    en: 'Fold the laundry',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 3,
    xp: 35,
    minAge: 9,
    maxAge: 16,
  },
  {
    es: 'Pasar la aspiradora',
    en: 'Vacuum the floor',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 3,
    xp: 40,
    minAge: 9,
    maxAge: 18,
  },
  {
    es: 'Sacar a pasear al perro',
    en: 'Walk the dog',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 3,
    xp: 40,
    minAge: 10,
    maxAge: 18,
  },
  {
    es: 'Lavar los platos',
    en: 'Wash the dishes',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 3,
    xp: 40,
    minAge: 10,
    maxAge: 18,
  },
  {
    es: 'Lavar el carro',
    en: 'Wash the car',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 6,
    xp: 50,
    minAge: 12,
    maxAge: 18,
  },
  {
    es: 'Limpiar el baño',
    en: 'Clean the bathroom',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 5,
    xp: 50,
    minAge: 12,
    maxAge: 18,
  },
  {
    es: 'Preparar una comida sencilla',
    en: 'Cook a simple meal',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 5,
    xp: 50,
    minAge: 13,
    maxAge: 18,
  },
  {
    es: 'Cortar el césped',
    en: 'Mow the lawn',
    group: 'home',
    category: 'chore',
    payType: 'both',
    amount: 8,
    xp: 60,
    minAge: 14,
    maxAge: 18,
  },

  // ── Study (lessons) ───────────────────────────────────────────
  {
    es: 'Practicar el abecedario',
    en: 'Practice the alphabet',
    group: 'study',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 25,
    minAge: 4,
    maxAge: 6,
  },
  {
    es: 'Leer un cuento con un adulto',
    en: 'Read a storybook with an adult',
    group: 'study',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 30,
    minAge: 4,
    maxAge: 7,
  },
  {
    es: 'Contar hasta 100',
    en: 'Count to 100',
    group: 'study',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 25,
    minAge: 5,
    maxAge: 7,
  },
  {
    es: 'Leer 20 minutos',
    en: 'Read for 20 minutes',
    group: 'study',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 40,
    minAge: 7,
    maxAge: 14,
  },
  {
    es: 'Aprender 5 palabras nuevas',
    en: 'Learn 5 new words',
    group: 'study',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 35,
    minAge: 7,
    maxAge: 14,
  },
  {
    es: 'Practicar las tablas de multiplicar',
    en: 'Practice multiplication tables',
    group: 'study',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 40,
    minAge: 8,
    maxAge: 11,
  },
  {
    es: 'Practicar un instrumento 20 min',
    en: 'Practice an instrument for 20 min',
    group: 'study',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 45,
    minAge: 7,
    maxAge: 18,
  },
  {
    es: 'Practicar otro idioma 15 min',
    en: 'Practice another language 15 min',
    group: 'study',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 40,
    minAge: 9,
    maxAge: 18,
  },
  {
    es: 'Escribir en un diario',
    en: 'Write in a journal',
    group: 'study',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 35,
    minAge: 9,
    maxAge: 18,
  },
  {
    es: 'Ver un documental educativo',
    en: 'Watch an educational documentary',
    group: 'study',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 30,
    minAge: 9,
    maxAge: 18,
  },
  {
    es: 'Repasar para un examen',
    en: 'Study for a test',
    group: 'study',
    category: 'lesson',
    payType: 'both',
    amount: 2,
    xp: 50,
    minAge: 10,
    maxAge: 18,
  },
  {
    es: 'Investigar un tema y resumirlo',
    en: 'Research a topic and summarize it',
    group: 'study',
    category: 'lesson',
    payType: 'both',
    amount: 2,
    xp: 50,
    minAge: 12,
    maxAge: 18,
  },

  // ── Homework (lessons) ────────────────────────────────────────
  {
    es: 'Preparar la mochila para mañana',
    en: 'Pack the backpack for tomorrow',
    group: 'homework',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 25,
    minAge: 5,
    maxAge: 12,
  },
  {
    es: 'Hacer la tarea de la escuela',
    en: 'Do your homework',
    group: 'homework',
    category: 'lesson',
    payType: 'both',
    amount: 2,
    xp: 40,
    minAge: 6,
    maxAge: 18,
  },
  {
    es: 'Terminar la tarea de matemáticas',
    en: 'Finish math homework',
    group: 'homework',
    category: 'lesson',
    payType: 'both',
    amount: 2,
    xp: 40,
    minAge: 7,
    maxAge: 16,
  },
  {
    es: 'Terminar la tarea de lectura',
    en: 'Finish reading homework',
    group: 'homework',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 40,
    minAge: 7,
    maxAge: 14,
  },
  {
    es: 'Terminar la tarea de ciencias',
    en: 'Finish science homework',
    group: 'homework',
    category: 'lesson',
    payType: 'both',
    amount: 2,
    xp: 40,
    minAge: 9,
    maxAge: 16,
  },
  {
    es: 'Repasar los apuntes del día',
    en: "Review the day's notes",
    group: 'homework',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 35,
    minAge: 11,
    maxAge: 18,
  },
  {
    es: 'Entregar un proyecto a tiempo',
    en: 'Turn in a project on time',
    group: 'homework',
    category: 'lesson',
    payType: 'both',
    amount: 5,
    xp: 60,
    minAge: 10,
    maxAge: 18,
  },
  {
    es: 'Escribir un ensayo',
    en: 'Write an essay',
    group: 'homework',
    category: 'lesson',
    payType: 'both',
    amount: 3,
    xp: 55,
    minAge: 13,
    maxAge: 18,
  },

  // ── Financial ─────────────────────────────────────────────────
  {
    es: 'Guardar $1 en tu alcancía',
    en: 'Save $1 in your piggy bank',
    group: 'financial',
    category: 'chore',
    payType: 'xp',
    amount: 0,
    xp: 30,
    minAge: 4,
    maxAge: 8,
  },
  {
    es: 'Contar tus ahorros',
    en: 'Count your savings',
    group: 'financial',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 25,
    minAge: 6,
    maxAge: 12,
  },
  {
    es: 'Resistir una compra impulsiva',
    en: 'Resist an impulse buy',
    group: 'financial',
    category: 'chore',
    payType: 'xp',
    amount: 0,
    xp: 50,
    minAge: 7,
    maxAge: 18,
  },
  {
    es: 'Ahorrar el 10% de tu mesada',
    en: 'Save 10% of your allowance',
    group: 'financial',
    category: 'chore',
    payType: 'xp',
    amount: 0,
    xp: 40,
    minAge: 8,
    maxAge: 18,
  },
  {
    es: 'Hacer una lista antes de comprar',
    en: 'Make a list before shopping',
    group: 'financial',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 30,
    minAge: 8,
    maxAge: 16,
  },
  {
    es: 'Apartar dinero para una meta',
    en: 'Set money aside for a goal',
    group: 'financial',
    category: 'chore',
    payType: 'xp',
    amount: 0,
    xp: 40,
    minAge: 8,
    maxAge: 18,
  },
  {
    es: 'Donar a una causa',
    en: 'Donate to a cause',
    group: 'financial',
    category: 'chore',
    payType: 'xp',
    amount: 0,
    xp: 40,
    minAge: 8,
    maxAge: 18,
  },
  {
    es: 'Comparar precios de 2 productos',
    en: 'Compare prices of 2 products',
    group: 'financial',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 35,
    minAge: 9,
    maxAge: 18,
  },
  {
    es: 'Llevar registro de tus gastos',
    en: 'Track your spending',
    group: 'financial',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 40,
    minAge: 10,
    maxAge: 18,
  },
  {
    es: 'Ganar dinero extra con una tarea',
    en: 'Earn extra with an odd job',
    group: 'financial',
    category: 'chore',
    payType: 'both',
    amount: 5,
    xp: 40,
    minAge: 12,
    maxAge: 18,
  },
  {
    es: 'Hacer un presupuesto semanal',
    en: 'Make a weekly budget',
    group: 'financial',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 50,
    minAge: 13,
    maxAge: 18,
  },
  {
    es: 'Investigar cómo crece el interés',
    en: 'Learn how interest grows',
    group: 'financial',
    category: 'lesson',
    payType: 'xp',
    amount: 0,
    xp: 45,
    minAge: 14,
    maxAge: 18,
  },
];

/** Suggestions for an age (or all when age is unknown/0), optionally one group. */
export function filterSuggestions(age: number, group?: SuggestionGroup): TaskSuggestion[] {
  return TASK_SUGGESTIONS.filter(
    (s) =>
      (group == null || s.group === group) && (age <= 0 || (age >= s.minAge && age <= s.maxAge)),
  );
}
