export { isAuthError } from './auth-error';
export { type CreateClientOptions, createTrpcClient, makeQueryClient } from './client';
export {
  useApiHealth,
  useApproveTask,
  useChildHome,
  useChildTasks,
  useCreateChild,
  useCreateTask,
  useCreateTransaction,
  useDeleteChild,
  useDeleteTask,
  useLoginChild,
  useLoginParent,
  useMe,
  useMyChildren,
  useMyDashboard,
  usePendingApprovals,
  usePiggyBanks,
  useQuests,
  useRegisterParent,
  useRejectTask,
  useRequestPasswordReset,
  useResendVerification,
  useResetKidPassword,
  useResetPassword,
  useSavingsGoals,
  useSetChildActive,
  useSubmitTask,
  useTasks,
  useUpdateAllowance,
  useUpdateChild,
  useVerifyEmail,
} from './hooks';
export { ApiProvider, type ApiProviderProps } from './provider';
export {
  type AppRouter,
  type RouterInputs,
  type RouterOutputs,
  useTRPC,
  useTRPCClient,
} from './trpc';
