export { isAuthError } from './auth-error';
export { type CreateClientOptions, createTrpcClient, makeQueryClient } from './client';
export {
  useActivity,
  useApiHealth,
  useApproveTask,
  useChildHome,
  useChildTasks,
  useCompleteQuest,
  useContributeGoal,
  useCreateChild,
  useCreateGoal,
  useCreateTask,
  useCreateTransaction,
  useDeleteAccount,
  useDeleteChild,
  useDeleteGoal,
  useDeleteTask,
  useLoginChild,
  useLoginParent,
  useMe,
  useMyChildren,
  useMyDashboard,
  useMyPatterns,
  useMyQuests,
  useMyWins,
  useParentSettings,
  useParentSummary,
  usePendingApprovals,
  usePiggyBanks,
  useQuests,
  useRegisterParent,
  useRejectTask,
  useReports,
  useRequestAccountDeletion,
  useRequestPasswordReset,
  useResendVerification,
  useResetKidPassword,
  useResetPassword,
  useResistImpulse,
  useSavingsGoals,
  useSetChildActive,
  useSubmitTask,
  useTasks,
  useUpdateAllowance,
  useUpdateChild,
  useUpdateParentSettings,
  useVerifyEmail,
} from './hooks';
export { ApiProvider, type ApiProviderProps } from './provider';
export {
  type AppRouter,
  type RouterInputs,
  type RouterOutputs,
  useTRPC,
  useTRPCClient,
} from './trpc';
